name: tds project action
on:
  workflow_dispatch: # Allows manual triggering
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 21f2000370@ds.study.iitm.ac.in
        run: echo "Hello, world!"
